### ISSUE TITLE
Not able to make it run locally

### ISSUE THREAD

**Issue by peterschneider** [mishig25/3d-posenet#4]
Uncaught SyntaxError: Unexpected identifier  (app.js:1)
Any idea?

**Comment by lucyd42** [comment]
Hey Peter,
- Do you have react.js?
- Are you running the code in a local server?

I was able to run this on my debian 10 machine by first correctly installing the 'yarn' command in my terminal. The default yarn I had was another program called 'cmd test' . I uninstalled it, installed correct 'yarn'. Switch to repo directory, and run 'yarn' and 'yarn watch' in your linux terminal.
